### ISSUE TITLE
Solid Leercredential uitbreidingen: authenticiteit en uitgever

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLOthema-Leercredential#2]
De Solid MVP Leercredential maakt gebruik van een implementatiemodel [Solid Leercredential](https://solid.data.vlaanderen.be/doc/implementatiemodel/leercredential/) gebaseerd op ELM. Dit implementatiemodel maakt dan ook hoofdzakelijk gebruik van de externe ELM URI's. 

Er zijn echter twee properties die gedefinieerd zijn in een eigen [implementatievocabularium](https://solid.data.vlaanderen.be/ns/leercredential), zijnde:
- {elm:Claim solid:authenticiteit skos:Concept}
- {elm:Claim solid:uitgever dct:Agent}

De _authenticiteit_ property komt uit de LED-taxonomie en bevat info over de provenance van de claim; die kan "authentiek" zijn en gemaakt door een "erkende" instelling of op "op eer - eigen verklaring" zijn.

De _uitgever_ property beschrijft de Agent die de claim maakt, i.e. de Leverancier uit de LED-taxonomie. Merk op dat deze kan verschillen van de uitgever van de Verifiable Credential.

Beide properties zijn suggesties om mogelijks op te nemen in het AP en VOC Leercredential.

**Comment by s-minoo** [comment]
Voor de *authenticiteit* property van elm:Claim, wordt het op dit moment op een *indirecte* manier bewezen door 
ToekenningsProcess (die uitgevoerd wordt door een "erkende" OSLO:Organisatie). 

Dus, de connectie ziet er zo uit voor  de *authenticiteit* van een LeerClaim:      
`LeerClaim <-> ToekenningsProcess  <- OSLO:Organisatie.`

Is het dan nog nodig om de *authenticiteit* nog een keer te toevoegen als een property voor LeerClaim?   
Zelfde geldt voor de *uitgever*. 
Het verschil kunt je checken voor de wettelijke identifiers van de Organistatie die de toekenningsprocess uitvoerde.

**Comment by dimi-schepers** [comment]
### Authenticiteit
Ik denk dat er voor leerbewijzen "op eer - eigen verklaring" geen uitvoerende organisatie is van het Toekenningproces, maar dit zou je eens moeten dubbelchecken bij de LED.

### Uitgever
Die Leerclaim.uitgever hebben wij toegevoegd omdat we nog een extra niveau van organisaties hadden in de brondata.
2 voorbeelden om dit te verduidelijken.

**Voorbeeld 1**
- Toekenningsproces.uitgevoerdDoor: KULeuven
- Leerclaim.uitgever: AHOVOKS
- Leercredential.uitgever: MAGDA

**Voorbeeld 2**
- Toekenningsproces.uitgevoerdDoor: Australian College of Optometry
- Leerclaim.uitgever: NARIC-Vlaanderen
- Leercredential.uitgever: MAGDA

**Comment by s-minoo** [comment]
Commit [7f1644d](https://github.com/Informatievlaanderen/OSLOthema-Leercredential/commit/7f1644de135c34e1740adc2f3fbee3c795e691b9) voegt de Leerclaim.uitgever toe als een extra association/property met OSLO:Organisatie en ook Leerclaim.authenticiteit
