### ISSUE TITLE
Persoon.heeftClaim ipv Persoon.claimt

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLOthema-Leercredential#3]
Ik zou willen voorstellen om het label van Persoon.claimt aan te passen naar Persoon.heeftClaim. Dit is ook een betere vertaling van de gebruikte URI, nl. `http://data.europa.eu/snb/model/elm/hasClaim`. In het verleden gebruikte ELM ook _claims_ maar dit is aangepast in de finale versie.

Deze terminologie is ook beter in lijn met de definitie van oslo:Leerclaim en elm:Claim, nl. "A claim made by an issuer", die zegt dat de claim niet per se gemaakt is door de betreffende Persoon maar mogelijks door een andere Agent. Zie ook het voorstel in issue #2 om deze Agent ook op te nemen in het AP.

**Comment by s-minoo** [comment]
Commit [c2cc631](https://github.com/Informatievlaanderen/OSLOthema-Leercredential/commit/c2cc6319be3363f4577ddd163f31c978cdccdba0)  fixes the issue
